<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Firstentries_atlit_model extends CI_Model
{

    public $table = 'firstentries_atlit';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }



    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('kelas', $q);
        $this->db->or_like('kategori', $q);
        $this->db->or_like('peserta', $q);
        $this->db->or_like('gender', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('kelas', $q);
        $this->db->or_like('kategori', $q);
        $this->db->or_like('peserta', $q);
        $this->db->or_like('gender', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    //perbaiki sesuai inputan
    // public function count_cadet_laki()
    // {
    //     $this->db->select('SUM(peserta) as jumlah');
    //     $this->db->from('firstentries_atlit');
    //     $this->db->where('gender', 'Laki - Laki');
    //     $this->db->where('kelas', 'cadet');
    //     $this->db->group_by('gender');
    //     $query = $this->db->get();
    //     return $query->row()->jumlah;
    // }

    // public function count_cadet_perempuan()
    // {
    //     $this->db->select('SUM(peserta) as jumlah');
    //     $this->db->from('firstentries_atlit');
    //     $this->db->where('gender', 'perempuan');
    //     $this->db->where('kelas', 'cadet');
    //     $this->db->group_by('gender');
    //     $query = $this->db->get();
    //     return $query->row()->jumlah;
    }
}

/* End of file Firstentries_atlit_model.php */
/* Location: ./application/models/Firstentries_atlit_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-03-18 05:53:04 */
/* http://harviacode.com */